# Generated by Django 5.1.7 on 2025-03-17 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='Unknown Faculty', max_length=100)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('research_areas', models.TextField(blank=True, null=True)),
                ('available_positions', models.IntegerField(default=1)),
                ('filled_positions', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchingRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('matched_count', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Unknown Organization', max_length=128)),
                ('area_of_law', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('available_positions', models.IntegerField(default=1)),
                ('filled_positions', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(default='Unknown', max_length=100)),
                ('last_name', models.CharField(default='Student', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('program', models.CharField(blank=True, max_length=128, null=True)),
                ('areas_of_law', models.TextField(blank=True, null=True)),
                ('location_preferences', models.TextField(blank=True, null=True)),
                ('work_preferences', models.TextField(blank=True, null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('admin_approval_needed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constitutional_law', models.CharField(blank=True, max_length=3, null=True)),
                ('contracts', models.CharField(blank=True, max_length=3, null=True)),
                ('criminal_law', models.CharField(blank=True, max_length=3, null=True)),
                ('property_law', models.CharField(blank=True, max_length=3, null=True)),
                ('torts', models.CharField(blank=True, max_length=3, null=True)),
                ('lrw_case_brief', models.CharField(blank=True, max_length=5, null=True)),
                ('lrw_multiple_case', models.CharField(blank=True, max_length=5, null=True)),
                ('lrw_short_memo', models.CharField(blank=True, max_length=5, null=True)),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='sail.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='')),
                ('area_of_law', models.CharField(blank=True, max_length=128, null=True)),
                ('statement_grade', models.IntegerField(blank=True, null=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='sail.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
