# Generated by Django 5.1.7 on 2025-03-17 22:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('areas_of_law', models.JSONField(default=list)),
                ('location', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('available_positions', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_names', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('program', models.CharField(max_length=255)),
                ('location_preferences', models.JSONField(default=list)),
                ('work_preferences', models.JSONField(default=list)),
                ('areas_of_interest', models.JSONField(default=list)),
                ('area_rankings', models.JSONField(default=dict)),
                ('is_self_proposed', models.BooleanField(default=False)),
                ('self_proposed_org', models.CharField(blank=True, max_length=255, null=True)),
                ('self_proposed_area', models.CharField(blank=True, choices=[('SJHR', 'Social Justice and Human Rights Law'), ('PIL', 'Public Interest Law'), ('PCL', 'Private/Civil Law'), ('IL', 'International Law'), ('EL', 'Environmental Law'), ('LL', 'Labour Law'), ('FL', 'Family Law'), ('BL', 'Business Law'), ('IP', 'Intellectual Property')], max_length=50, null=True)),
                ('self_proposed_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('self_proposed_role', models.CharField(blank=True, max_length=255, null=True)),
                ('self_proposed_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('self_proposed_contact', models.TextField(blank=True, null=True)),
                ('self_proposed_statement', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'given_names'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constitutional_law', models.CharField(blank=True, max_length=2, null=True)),
                ('contracts', models.CharField(blank=True, max_length=2, null=True)),
                ('criminal_law', models.CharField(blank=True, max_length=2, null=True)),
                ('property_law', models.CharField(blank=True, max_length=2, null=True)),
                ('torts', models.CharField(blank=True, max_length=2, null=True)),
                ('case_brief', models.CharField(blank=True, max_length=2, null=True)),
                ('multiple_case_analysis', models.CharField(blank=True, max_length=2, null=True)),
                ('short_legal_memo', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_pdf', models.FileField(blank=True, null=True, upload_to='grades/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='admin_portal.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_law', models.CharField(choices=[('SJHR', 'Social Justice and Human Rights Law'), ('PIL', 'Public Interest Law'), ('PCL', 'Private/Civil Law'), ('IL', 'International Law'), ('EL', 'Environmental Law'), ('LL', 'Labour Law'), ('FL', 'Family Law'), ('BL', 'Business Law'), ('IP', 'Intellectual Property')], max_length=50)),
                ('content', models.TextField()),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='admin_portal.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'area_of_law')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_law', models.CharField(choices=[('SJHR', 'Social Justice and Human Rights Law'), ('PIL', 'Public Interest Law'), ('PCL', 'Private/Civil Law'), ('IL', 'International Law'), ('EL', 'Environmental Law'), ('LL', 'Labour Law'), ('FL', 'Family Law'), ('BL', 'Business Law'), ('IP', 'Intellectual Property')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='admin_portal.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='admin_portal.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'organization', 'area_of_law')},
            },
        ),
    ]
