# Generated by Django 5.1.7 on 2025-03-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='final_reflection_path',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='learning_plan_path',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='midpoint_checkin_path',
        ),
    ]
